services:
  latex-builder:
    build:
      context: ..
      dockerfile: ../Dockerfile
      args:
        TEX_FILE: test.tex
        BUILD_FORMAT: pdf
    container_name: latex-builder
    volumes:
      - ./:/work
    environment:
      TEX_FILE: test.tex
      BUILD_FORMAT: pdf
